### ISSUE TITLE
Packages failed to restore: Package Moq.Dapper 1.0.7 is not compatible with net80

### ISSUE THREAD

**Issue by LucasLopesr** [UnoSD/Moq.Dapper#95]
I had problems restoring test packages using "Moq.Dapper" using Azure Pipeline

SDK version net8.0

Command:
```  
    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: restore
        projects: '*.sln'
```

![image](https://github.com/UnoSD/Moq.Dapper/assets/15997657/fea8105f-bb6b-4854-9d42-068fb5a25c6c)
